name = "futsal-api"
main = "api/index.js"
compatibility_date = "2023-01-16"

[site]
bucket = "./assets"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
	{ pattern = "api.futsal.dev", custom_domain = true }
]